# Generated by Django 4.2.23 on 2025-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('type', models.CharField(max_length=100, verbose_name='Тип тренировки')),
            ],
        ),
    ]
