# Generated by Django 4.2.23 on 2025-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_coach_leveltag_location_trainingdirection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='direction',
        ),
        migrations.AddField(
            model_name='coach',
            name='directions',
            field=models.ManyToManyField(related_name='coaches', to='trainings.trainingdirection'),
        ),
    ]
