# Generated by Django 4.2.23 on 2025-07-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_remove_coach_direction_coach_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
        migrations.AddField(
            model_name='coach',
            name='instagram',
            field=models.CharField(blank=True, help_text='Имя пользователя без @ или ссылка', max_length=100),
        ),
    ]
