# Generated by Django 4.2.23 on 2025-09-20 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0004_remove_coach_user_coach_instagram"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Название тарифа"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Индивидуальные outdoor"),
                            ("mini_group", "Мини-группы"),
                            ("athlete", "Группы для спортсменов"),
                            ("kids", "Группы для детей"),
                        ],
                        max_length=32,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Стоимость"
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=80, verbose_name="Периодичность"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Выделенный тариф"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Тариф на тренировки",
                "verbose_name_plural": "Тарифы на тренировки",
                "ordering": ["category", "order", "price"],
            },
        ),
        migrations.AlterModelOptions(
            name="coach",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.AlterModelOptions(
            name="leveltag",
            options={
                "ordering": ["tag"],
                "verbose_name": "Уровень подготовки",
                "verbose_name_plural": "Уровни подготовки",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["title"],
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.AlterModelOptions(
            name="training",
            options={
                "verbose_name": "Тренировка (legacy)",
                "verbose_name_plural": "Тренировки (legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="trainingdirection",
            options={
                "ordering": ["title"],
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.AlterModelOptions(
            name="trainingsession",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Сеанс тренировки",
                "verbose_name_plural": "Расписание тренировок",
            },
        ),
        migrations.AddField(
            model_name="coach",
            name="achievements",
            field=models.TextField(blank=True, verbose_name="Достижения"),
        ),
        migrations.AddField(
            model_name="coach",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="coach",
            name="experience_years",
            field=models.PositiveIntegerField(
                default=0, help_text="Полные годы опыта", verbose_name="Опыт (лет)"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Выводить на главной"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="coach",
            name="role",
            field=models.CharField(blank=True, max_length=120, verbose_name="Роль"),
        ),
        migrations.AddField(
            model_name="coach",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=140, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя или ссылка",
                max_length=100,
                verbose_name="Telegram",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AddField(
            model_name="trainingdirection",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="trainingdirection",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="CSS-класс или emoji",
                max_length=120,
                verbose_name="Иконка",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="color",
            field=models.CharField(
                blank=True,
                default="#006CFF",
                max_length=20,
                verbose_name="Цвет в календаре",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="intensity",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Интенсивность"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="registration_link",
            field=models.URLField(blank=True, verbose_name="Ссылка на запись"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="spots_available",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 если запись закрыта",
                verbose_name="Свободных мест",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="spots_total",
            field=models.PositiveIntegerField(default=0, verbose_name="Всего мест"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="title",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Название занятия"
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coach",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="directions",
            field=models.ManyToManyField(
                related_name="coaches",
                to="trainings.trainingdirection",
                verbose_name="Направления",
            ),
        ),
        migrations.AlterField(
            model_name="coach",
            name="full_name",
            field=models.CharField(max_length=120, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="coach",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Имя пользователя или ссылка",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="coach",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="coaches/photos/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="leveltag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("beginner", "Начальный"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                    ("any", "Любой уровень"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название локации"),
        ),
        migrations.AlterField(
            model_name="trainingdirection",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название направления"),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="trainings.coach",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="direction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="trainings.trainingdirection",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="end_time",
            field=models.TimeField(verbose_name="Окончание"),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="levels",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="trainings.leveltag"
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="trainings.location",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="start_time",
            field=models.TimeField(verbose_name="Начало"),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="type",
            field=models.CharField(
                choices=[
                    ("group", "Групповая"),
                    ("mini_group", "Мини-группа"),
                    ("open", "Открытая"),
                    ("personal", "Индивидуальная"),
                ],
                max_length=15,
                verbose_name="Формат",
            ),
        ),
        migrations.CreateModel(
            name="TrainingPlanBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Преимущество")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="trainings.trainingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество тарифа",
                "verbose_name_plural": "Преимущества тарифов",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Заголовок"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="trainings/attachments/", verbose_name="Файл"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="trainings.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал тренировки",
                "verbose_name_plural": "Материалы тренировки",
            },
        ),
    ]
