# Generated by Django 4.2.23 on 2025-11-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_trainingplan_category_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('category', models.CharField(blank=True, choices=[('personal', 'Индивидуальные'), ('group', 'Групповые'), ('subscription', 'Абонементы'), ('service', 'Сервисы и опции')], max_length=32, verbose_name='Тип тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделить')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тариф занятия',
                'verbose_name_plural': 'Тарифы занятий',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTariffPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: занятие с конкретным тренером или количество посещений', max_length=180, verbose_name='Описание стоимости')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='trainings.sessiontariff')),
            ],
            options={
                'verbose_name': 'Стоимость тарифа занятия',
                'verbose_name_plural': 'Стоимость тарифа занятия',
                'ordering': ['order', 'id'],
            },
        ),
    ]
