# Generated by Django 4.2.23 on 2026-06-12 14:08

from django.db import IntegrityError
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def populate_direction_slugs(apps, schema_editor):
    TrainingDirection = apps.get_model("trainings", "TrainingDirection")

    for direction in TrainingDirection.objects.order_by("id"):
        if direction.slug:
            continue

        base_slug = slugify(direction.title, allow_unicode=True) or "direction"
        candidate = base_slug
        suffix = 2

        while TrainingDirection.objects.filter(slug=candidate).exclude(
            pk=direction.pk
        ).exists():
            candidate = f"{base_slug}-{suffix}"
            suffix += 1

        direction.slug = candidate
        try:
            direction.save(update_fields=["slug"])
        except IntegrityError:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_sessiontariff_sessiontariffprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdirection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Польза от тренировок'),
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='first_session_details',
            field=models.TextField(blank=True, verbose_name='Что будет на первом занятии'),
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='trainingdirection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется в адресе страницы направления', max_length=140, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название локации'),
        ),
        migrations.CreateModel(
            name='TrainingDirectionTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_tariffs', to='trainings.trainingdirection')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_links', to='trainings.sessiontariff')),
            ],
            options={
                'verbose_name': 'Тариф направления',
                'verbose_name_plural': 'Тарифы направлений',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDirectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trainings/directions/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trainings.trainingdirection')),
            ],
            options={
                'verbose_name': 'Фотография направления',
                'verbose_name_plural': 'Фотографии направлений',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDirectionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_locations', to='trainings.trainingdirection')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_links', to='trainings.location')),
            ],
            options={
                'verbose_name': 'Локация направления',
                'verbose_name_plural': 'Локации направлений',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingdirectiontariff',
            constraint=models.UniqueConstraint(fields=('direction', 'tariff'), name='unique_training_direction_tariff'),
        ),
        migrations.AddConstraint(
            model_name='trainingdirectionlocation',
            constraint=models.UniqueConstraint(fields=('direction', 'location'), name='unique_training_direction_location'),
        ),
        migrations.RunPython(populate_direction_slugs, migrations.RunPython.noop),
    ]
