# Generated by Django 4.2.23 on 2026-06-22 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def _build_unique_slug(model_class, title, pk, fallback):
    base_slug = slugify(title, allow_unicode=True) or fallback
    slug = base_slug
    suffix = 2

    while model_class.objects.exclude(pk=pk).filter(slug=slug).exists():
        slug = f"{base_slug}-{suffix}"
        suffix += 1

    return slug


def populate_tariff_slugs(apps, schema_editor):
    TrainingPlan = apps.get_model("trainings", "TrainingPlan")
    SessionTariff = apps.get_model("trainings", "SessionTariff")

    for plan in TrainingPlan.objects.all().iterator():
        if not plan.slug:
            plan.slug = _build_unique_slug(
                TrainingPlan, plan.title, plan.pk, "training-plan"
            )
            plan.save(update_fields=["slug"])

    for tariff in SessionTariff.objects.all().iterator():
        if not tariff.slug:
            tariff.slug = _build_unique_slug(
                SessionTariff, tariff.title, tariff.pk, "session-tariff"
            )
            tariff.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_seed_staging_session_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontariff',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется в адресе страницы тарифа', max_length=180, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='sessiontariff',
            name='video_file',
            field=models.FileField(blank=True, help_text='Необязательно. Поддерживаются MP4, WebM, MOV и M4V.', upload_to='trainings/session-tariffs/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='sessiontariff',
            name='video_vk_embed_url',
            field=models.URLField(blank=True, help_text='Необязательно. Вставьте embed-ссылку VK Видео. Если заполнены и ссылка, и файл, на сайте будет показано VK-видео.', verbose_name='Ссылка на VK Видео'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='slug',
            field=models.SlugField(blank=True, help_text='Используется в адресе страницы тарифа', max_length=180, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='video_file',
            field=models.FileField(blank=True, help_text='Необязательно. Поддерживаются MP4, WebM, MOV и M4V.', upload_to='trainings/plans/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='video_vk_embed_url',
            field=models.URLField(blank=True, help_text='Необязательно. Вставьте embed-ссылку VK Видео. Если заполнены и ссылка, и файл, на сайте будет показано VK-видео.', verbose_name='Ссылка на VK Видео'),
        ),
        migrations.RunPython(populate_tariff_slugs, noop_reverse),
        migrations.CreateModel(
            name='TrainingPlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trainings/plans/gallery/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trainings.trainingplan')),
            ],
            options={
                'verbose_name': 'Фотография тарифа',
                'verbose_name_plural': 'Фотографии тарифов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTariffPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trainings/session-tariffs/gallery/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trainings.sessiontariff')),
            ],
            options={
                'verbose_name': 'Фотография тарифа занятия',
                'verbose_name_plural': 'Фотографии тарифов занятий',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionTariffBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Преимущество')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='trainings.sessiontariff')),
            ],
            options={
                'verbose_name': 'Преимущество тарифа занятия',
                'verbose_name_plural': 'Преимущества тарифов занятий',
                'ordering': ['order', 'id'],
            },
        ),
    ]
