# Generated by Django 4.2.23 on 2026-06-30 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_leveltag_custom_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontariffphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Медиа тарифа занятия', 'verbose_name_plural': 'Галерея тарифов занятий'},
        ),
        migrations.AlterModelOptions(
            name='trainingplanphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Медиа тарифа', 'verbose_name_plural': 'Галерея тарифов'},
        ),
        migrations.AddField(
            model_name='sessiontariffphoto',
            name='video_file',
            field=models.FileField(blank=True, help_text='Необязательно. Поддерживаются MP4, WebM, MOV и M4V.', upload_to='trainings/session-tariffs/gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='trainingplanphoto',
            name='video_file',
            field=models.FileField(blank=True, help_text='Необязательно. Поддерживаются MP4, WebM, MOV и M4V.', upload_to='trainings/plans/gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='sessiontariffphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='trainings/session-tariffs/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='trainingplanphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='trainings/plans/gallery/', verbose_name='Изображение'),
        ),
    ]
