# Generated by Django 4.2.23 on 2025-09-20 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camp",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Кэмп",
                "verbose_name_plural": "Кэмпы",
            },
        ),
        migrations.RemoveField(
            model_name="camp",
            name="image",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="price",
        ),
        migrations.AddField(
            model_name="camp",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camp",
            name="hero_image",
            field=models.ImageField(
                blank=True, upload_to="camps/hero/", verbose_name="Обложка"
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной"
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="price_from",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Минимальная стоимость участия",
                max_digits=8,
                verbose_name="Цена от",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camp",
            name="registration_link",
            field=models.URLField(blank=True, verbose_name="Ссылка на регистрацию"),
        ),
        migrations.AddField(
            model_name="camp",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("upcoming", "Анонс"),
                    ("completed", "Проведён"),
                ],
                default="upcoming",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="camp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="description",
            field=models.TextField(verbose_name="Полное описание"),
        ),
        migrations.CreateModel(
            name="CampHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Преимущество")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="camps.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность кэмпа",
                "verbose_name_plural": "Особенности кэмпа",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CampGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="camps/gallery/", verbose_name="Фото"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Подпись"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="camps.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото кэмпа",
                "verbose_name_plural": "Галерея кэмпа",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CampDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(default=1, verbose_name="День"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название дня"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program",
                        to="camps.camp",
                    ),
                ),
            ],
            options={
                "verbose_name": "День программы",
                "verbose_name_plural": "Программа кэмпа",
                "ordering": ["day_number"],
            },
        ),
    ]
