# Generated by Django 4.2.23 on 2025-09-20 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=60, unique=True, verbose_name="Тег"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=80, unique=True, verbose_name="Слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to="articles/", verbose_name="Обложка"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Время чтения (мин)"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_description",
            field=models.TextField(blank=True, verbose_name="SEO Description"),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="SEO Title"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=240, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="blog.articletag"
            ),
        ),
    ]
