# Generated by Django 4.2.23 on 2025-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
            ],
        ),
    ]
