# Generated by Django 4.2.23 on 2025-09-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Gabi Club",
                        max_length=160,
                        verbose_name="Название клуба",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=200, verbose_name="Слоган"),
                ),
                ("mission", models.TextField(blank=True, verbose_name="Миссия")),
                ("story", models.TextField(blank=True, verbose_name="История")),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год основания"
                    ),
                ),
                ("hero_video", models.URLField(blank=True, verbose_name="Видео")),
                (
                    "hero_description",
                    models.TextField(blank=True, verbose_name="Описание в герое"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO Title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="SEO Description"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Профиль клуба",
                "verbose_name_plural": "Профиль клуба",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Gabi Club",
                        max_length=120,
                        verbose_name="Название блока",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Основной телефон"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Дополнительный телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "map_url",
                    models.URLField(blank=True, verbose_name="Ссылка на карту"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="График работы"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Telegram"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Instagram"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="YouTube"
                    ),
                ),
                ("vk", models.CharField(blank=True, max_length=120, verbose_name="VK")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Заголовок"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="hero/", verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_slides",
                        to="core.clubprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд героя",
                "verbose_name_plural": "Слайды героя",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeadRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "preferred_direction",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Направление"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Источник"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка на тренировку",
                "verbose_name_plural": "Заявки на тренировку",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Название")),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS-класс или emoji",
                        max_length=60,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="core.contactinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
                "ordering": ["order", "title"],
            },
        ),
        migrations.DeleteModel(
            name="ContactLink",
        ),
    ]
