# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_clubprofile_contactinfo_heroslide_leadrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "primary_color",
                    models.CharField(default="#006CFF", max_length=7, verbose_name="Основной цвет"),
                ),
                (
                    "secondary_color",
                    models.CharField(default="#FF7A00", max_length=7, verbose_name="Акцентный цвет"),
                ),
                (
                    "gradient_start",
                    models.CharField(default="#006CFF", max_length=7, verbose_name="Градиент: начало"),
                ),
                (
                    "gradient_end",
                    models.CharField(default="#FF7A00", max_length=7, verbose_name="Градиент: конец"),
                ),
                (
                    "club_photo",
                    models.ImageField(blank=True, upload_to="theme/", verbose_name="Фото для формы"),
                ),
                (
                    "snow_bg",
                    models.ImageField(blank=True, upload_to="theme/", verbose_name="Фоновое фото (снег)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки темы",
                "verbose_name_plural": "Настройки темы",
            },
        ),
    ]

