# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_themesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="themesettings",
            name="background_color",
            field=models.CharField(default="#ECECEC", max_length=7, verbose_name="Цвет фона сайта"),
        ),
    ]

